Mobile portfolio Works and About sections
Nyame-Wolf/Portfolio pull request #2
Opened 2022-05-27 17:32 UTC by Nyame-Wolf

# Mobile portfolio Works and About sections
- Added works sections. Used Css grid to place the cards and flex box to place card contents
-  styled css list to buttons
- enabled hover effect on list buttons.

2022-05-27 18:41 UTC, Ismailco requested changes
### Hi @Nyame-Wolf,

Good job so far 👍🏼 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✔️  No linter errors
✔️ Used Github Flow
✔️ Work documented professionally

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-27 18:41 UTC, Ismailco commented on README.md
- [ ] Kindly add a project description to the README, so your documentation is more professional

2022-05-27 18:41 UTC, Ismailco commented on index.html
> +        <div id="item1">
- [ ] For better practices you can use semantic stages here e.g. ```<article>```, please try to minimalize the use of ```<div>``` in your code instead use ```<section>``` and ```<article>```

2022-05-27 18:41 UTC, Ismailco commented on index.html
> +      <section>
- [ ] You can use ```grid``` to style all the projects, starting with this project

2022-05-27 18:41 UTC, Ismailco commented on index.html
> +              <h4>Profesional Art Printing Data</h4>
- [ ] [OPTIONAL] Please consider using the same ```hx``` for the title of the projects

2022-05-27 18:41 UTC, Ismailco commented on style.css
> +.grid {
- [ ] You need to add the paragraph for the first project and align the ```See Project``` button to the left, please stick to the Figma design as much as possible

|Your design|Figma design|
|--|--|
|![Screenshot_20220527_192857](https://user-images.githubusercontent.com/25227022/170769989-94d147ab-a7b9-43d4-851b-f781358397d3.png)|![Screenshot_20220527_192956](https://user-images.githubusercontent.com/25227022/170770023-d654aee1-f62d-455d-a073-86d9aa0b5b16.png)|

2022-05-27 18:41 UTC, Ismailco commented on style.css
> +#item1 {
- [ ] The ```See project``` button should be at the bottom of the project card, please use the propper ``` margin/spacing``` and modify your design so it is as close as much to the Figma design

|Your design|Figma design|
|--|--|
|![Screenshot_20220527_192836](https://user-images.githubusercontent.com/25227022/170770367-bea34071-09f5-41e7-9f4f-2da9436e54c8.png)|![Screenshot_20220527_192940](https://user-images.githubusercontent.com/25227022/170770386-10e01068-fad8-4558-9779-1e10f2c1c252.png)|

2022-05-27 18:41 UTC, Ismailco commented on style.css
> +.about-li {
- [ ] The ```languages```, ```skills```, and ```framework``` items should be centered, please implement this and stick to the design as much as possible

|Your design|figma design|
|-|-|
|![Screenshot_20220527_192818](https://user-images.githubusercontent.com/25227022/170771206-ae8af759-bb25-430c-a741-6789c6785983.png)|![Screenshot_20220527_192921](https://user-images.githubusercontent.com/25227022/170771224-c25e9982-675d-40d8-9e5d-0cdfeff46658.png)|

2022-05-28 19:28 UTC, Div685 approved these changes
Hi, **@Nyame-Wolf**, I'm Divyesh your reviewer for this PR :man_technologist: 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Keep on coding! :muscle:

## Highlights

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Code review by **Divyesh Patel**.

_(Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.)_

------
>_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-28 19:28 UTC, Div685 commented on index.html
> +        <!-- <div class="grid"> -->
- [ ] [Optional] Please remove commented code. It makes your repo and your project unprofessional. if you still want to check the previous changes you made you can go back to the previous commits and check.

2022-05-28 19:42 UTC, merged